### ISSUE TITLE
Allow rule labels with slash

### ISSUE THREAD

**Issue by gordonbondon** [prometheus/common#180]
Spec for [PrometheusRule](https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/prometheusrule.crd.yaml#L231) notes that labels may match selectors of replication controllers and services. According to [this](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) labels like `app.kubernetes.io/name` are recommended for kubernetes. But apparantly `/` is not allowed [here](https://github.com/prometheus/common/blob/7600349dcfe1abd18d72d3a1770870d9800a7801/model/labels.go#L86) and I get errors like this:
```
level=error ts=2019-03-21T14:32:57.642600466Z caller=manager.go:754 component="rule manager" msg="loading groups failed" err="group \"analytics-csgo-stats-api-dev.rules\", rule 0, \"5xxErrors\": invalid label name: app.kubernetes.io/name"
```

**Comment by brian-brazil** [comment]
You've got the wrong repo, you're looking for the Prometheus Operator.

**Comment by gordonbondon** [comment]
Operator does not validate rules itself. So I get this error when rule is added prometheus config and probably bparsed by this package [here](https://github.com/prometheus/prometheus/blob/master/pkg/rulefmt/rulefmt.go#L130).

I understand that prometheus is not part of kubernetes but still,
is it possible to allow `/` symbols so it's possible to use such labels? Or there is some limitation?

**Comment by brian-brazil** [comment]
The characters allowed in labelnames will not change from a Prometheus standpoint. This does sound like an Operator issue.

**Comment by gordonbondon** [comment]
Sorry, I did not provide more details. I was meant rules labels like here:
```
- name: somename
      rules:
        - alert: "AnalyticsCsgoStats5xxErrors" 
          annotations:
            description: "Increased 5xx error rate on {{ $labels.namespace }}/{{ $labels.service }}"
            expr: increase(analytics_csgo_stats_http_responses_total{code=~"5.*"}[1m]) > 0
          for: "5m"
          labels:
            severity: "warning"
            app.kubernetes.io/name: app-name
```

Currently, we have to switch `app.kubernetes.io/name` to `app` because / is not allowed.
