### ISSUE TITLE
Scrape - configure auth header scheme

### ISSUE THREAD

**Issue by dazinator** [prometheus/common#271]
## Proposal
Allow Authorization header 'scheme' name and value to be configured.

Right now, I can either configure `Basic` authentication or `Bearer` authentication. Depending on which I configure, dictates the scheme name prefix in the auth header on the scrape request. For example prometheus can be configured to send either of these headers:

- Authorization: BASIC hwhhejfjjjejdnwje
- Authorization: BEARER hwhhejfjjjejdnwje

Each option essentialy places a constraint on the 'scheme name' portion of the authorization header, whilst allowing a static value / token to be passed as the credentials portion. This means I can configure a static value to be passed for the credentials only limited to "Basic" or "Bearer" schemes.

I have an application that uses a custom authentication scheme called API key authentication. This is also a static value that must be passed in the Authorization header. The difference is it requires a custom scheme name 'ApiKey`. I'd like prometheus to allow me to specify the scheme name, so that I am not limited to Basic or Bearer schemes and can use a custom scheme name.

Sure I could set up a custom proxy but this introduces another moving part and more complexity in the landscape so I am thinking this should be weighed against alternatives. Being able to configure the scheme name (as opposed to being restricted to Basic and Bearer) would provide for a more general purpose implementation that makes prometheus more flexible and covers more use cases without much additional complexity that I can tell..

For example right now the following two auth headers are configurable but the third is not.

- Authorization: BASIC hwhhejfjjjejdnwje
- Authorization: BEARER hwhhejfjjjejdnwje
- Authorization: API-KEY hwhhejfjjjejdnwje

I beleive that allowing an authorization header to be configured - by specifying its components:

- scheme name
- value

.. would make for a more flexibile option to cover more use cases.

*“Nice to have” is not a good use case. :)*

We have a .net core web api we'd like to scrape that doesn't support basic auth and only supports short lived access tokens using the BEARER authentication scheme. It does support a custom Authorization scheme for api key authentication (which is a long lived value) however prometheus is currently not able to be configured to leverage that.

**Comment by roidelapluie** [comment]
I have opened the following pull request: https://github.com/prometheus/common/pull/272 to gather feedback from other team members.

**Comment by dazinator** [comment]
I see the PR has now been merged - thank you for implementing this @roidelapluie

**Comment by roidelapluie** [comment]
#274 will still be needed before I can push it down to prometheus

**Comment by dazinator** [comment]
@roidelapluie looks like #274 was merged - can this now be considered closed?
I am new to prometheus, is there a nightly release I can get from somewhere that would have these changes?

**Comment by roidelapluie** [comment]
You could test with the docker image prom/prometheus:main or take a binary from ci https://app.circleci.com/pipelines/github/prometheus/prometheus/11049/workflows/c4a4c2d1-2288-429a-afa2-9ad06cb64578/jobs/48406/artifacts

Note: for testing only.

It would be nice to get feedback if it works as expected.

**Comment by qmonitoring** [comment]
> 
> 
> You could test with the docker image prom/prometheus:main or take a binary from ci https://app.circleci.com/pipelines/github/prometheus/prometheus/11049/workflows/c4a4c2d1-2288-429a-afa2-9ad06cb64578/jobs/48406/artifacts
> 
> Note: for testing only.
> 
> It would be nice to get feedback if it works as expected.

@roidelapluie  thank you for your work!

**Could you please clarify how to use APIKEY token?**

I am trying to scrape an endpoint with an API KEY аuthorization.

_prom/prometheus:main_ is up and running:

`docker run -d --network=host --name=prometheus -v /path/prometheus.yml:/etc/prometheus/prometheus.yml  prom/prometheus:main --config.file=/etc/prometheus/prometheus.yml --web.listen-address=:9095  `

with the following prometheus.yml configuration file:

```
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: prometheus_in_docker
	
scrape_configs:

  - job_name: json_exporter_self
    static_configs:
      - targets:
        - <host>:7979 ## Location of the json exporter's real <hostname>:<port>

  ## gather the metrics from third party json sources, via the json exporter
  - job_name: json_exporter_data
    metrics_path: /probe
    authorization:
      credentials: '{my_secret_token}'
      type: apikey	
    static_configs:
      - targets:
        - http://<endpoint_host>:<port>/api/v1/data
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <host>:7979 ## Location of the json exporter's real <hostname>:<port>
```
for jsons exporting I use the [prometheus-community/json_exporter](https://github.com/prometheus-community/json_exporter)
with the following config.yml configuration file:

```
metrics:
- name: example_metric
  path: "{ .data }"
  help: Example 
  labels:
    environment: testdata # static label
```

Self scraping works fine (_http://<host>:7979/metrics_), but a json scraping doesn't work (_http://<host>:7979/probe_), the error is the following:

_Failed to fetch JSON response. TARGET: http://<endpoint_host>:<port>/api/v1/data, ERROR: 401 Unauthorized_

The endpoint itself is available:
`curl -X GET 'http://<endpoint_host>:<port>/api/v1/data' -H 'Authorization: {my_secret_token}'`

Is this a misconfiguration on my side? If yes, how can I fix this?
